//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsnovnaSkola
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelOsnovnaSkolaContainer : DbContext
    {
        public ModelOsnovnaSkolaContainer()
            : base("name=ModelOsnovnaSkolaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Zaposleni> Zaposlenici { get; set; }
        public virtual DbSet<Kontrolna_tacka> Kontrolna_tacka { get; set; }
        public virtual DbSet<Predavanje> Predavanja { get; set; }
        public virtual DbSet<Oblast> Oblasti { get; set; }
        public virtual DbSet<Cas> Cas { get; set; }
        public virtual DbSet<Predmet> Predmeti { get; set; }
        public virtual DbSet<Odeljenje> Odeljenja { get; set; }
        public virtual DbSet<Ucenik> Ucenici { get; set; }
        public virtual DbSet<Odrzava> KontrolnaTackaCasovi { get; set; }
        public virtual DbSet<Ima> Imaju { get; set; }
        public virtual DbSet<Prisustvo> Prisustva { get; set; }
        public virtual DbSet<Radi> Rade { get; set; }
        public virtual DbSet<NastavnikOdeljenje> NastavnikOdeljenjes { get; set; }
    }
}
